### ISSUE TITLE
大佬，创建了，怎么在v2rayN里面填写参数，求教

### ISSUE THREAD

**Issue by limobai2333** [GeekNAUer/vlessheroku#1]

**Comment by limobai2333** [comment]
打开Heroku创建的网页，并没有提示Bad Request，而是提示找不到 xxx.herokuapp.com 的网页
难不成不可用？

**Comment by GeekNAUer** [comment]
可以用的

**Comment by GeekNAUer** [comment]
> ```
>              打开Heroku创建的网页，并没有提示Bad Request，而是提示找不到 xxx.herokuapp.com 的网页
> ```
> 
> 难不成不可用？

我提到过，协议是vless，path你要填/app
如果不可用，我不会放出来的

**Comment by ablebodied** [comment]
可以用，一下子就成功了，没想到如此顺利，感谢

**Comment by limobai2333** [comment]
这几天的使用感受，断流不明显，8K打开速度中等偏上开启，播放还算顺畅。
感谢大佬的无私奉献，本人两个链接是否需要全部更换成vless协议，还是vmess能用的话将就用着。影响大不之类等芸芸？

**Comment by GeekNAUer** [comment]
> 这几天的使用感受，断流不明显，8K打开速度中等偏上开启，播放还算顺畅。
> 感谢大佬的无私奉献，本人两个链接是否需要全部更换成vless协议，还是vmess能用的话将就用着。影响大不之类等芸芸？

vless在heroku上部署的人少，不容易被官方封

**Comment by csgowdnmd** [comment]
大佬能出个Trojan go的吗？

**Comment by echen1294** [comment]
出现了这个Bad Request，但到协议里填了没办法连，本人是超级小白，不知大佬能写个完整的教程吗？

**Comment by echen1294** [comment]
能帮忙提供一下v2rayN里面怎样填写参数吗？谢谢了。

**Comment by echen1294** [comment]
imobai2333你好，能麻烦教一下怎么用吗？
