### ISSUE TITLE
问一下，已经部署好的如何更新vcore？

### ISSUE THREAD

**Issue by eightsheep67** [GeekNAUer/vlessheroku#2]
问一下，已经部署好的如何更新vcore？

**Comment by GeekNAUer** [comment]
最简单的办法，删除之后重新部署，名称设置成和之前一样

**Comment by eightsheep67** [comment]
> 最简单的办法，删除之后重新部署，名称设置成和之前一样

OK！

**Comment by eightsheep67** [comment]
> 最简单的办法，删除之后重新部署，名称设置成和之前一样

还想问一下，如何能在heroku查看vcore版本呢

**Comment by GeekNAUer** [comment]
> > 最简单的办法，删除之后重新部署，名称设置成和之前一样
> 
> 还想问一下，如何能在heroku查看vcore版本呢

**Comment by GeekNAUer** [comment]
> > > 最简单的办法，删除之后重新部署，名称设置成和之前一样
> > 
> > 
> > 还想问一下，如何能在heroku查看vcore版本呢

安装的版本是你部署时最新的v2ray-core
